# Generated by Django 4.2.1 on 2023-07-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Shoe', 'Shoe'), ('Cloth', 'Cloth'), ('Electronic', 'Electronic')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'cloth',
            },
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Shoe', 'Shoe'), ('Cloth', 'Cloth'), ('Electronic', 'Electronic')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'electronic',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Shoe', 'Shoe'), ('Cloth', 'Cloth'), ('Electronic', 'Electronic')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.CharField(choices=[('Outdoor', 'Outdoor'), ('Indoor', 'Indoor'), ('Man', 'Man'), ('Woman', 'Woman'), ('Kids', 'Kids')], max_length=200, null=True)),
                ('size', models.CharField(choices=[('US 5', 'US 5'), ('US 6', 'US 6'), ('US 7', 'US 7'), ('US 9', 'US 9'), ('US 10', 'US 10'), ('US 11', 'US 11'), ('US 12', 'US 12'), ('US 13', 'US 13')], max_length=200, null=True)),
            ],
            options={
                'db_table': 'shoe',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
    ]
