# Generated by Django 4.2.1 on 2023-08-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dukkaana', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
