# Generated by Django 4.2.1 on 2023-07-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkaana', '0002_remove_cloth_image_remove_electronic_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='object_id',
            field=models.CharField(max_length=200),
        ),
    ]
