# Generated by Django 4.2.1 on 2023-07-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dukkaana', '0004_remove_productimage_content_type_cloth_custom_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='custom_id',
        ),
    ]
