# Generated by Django 4.2.1 on 2023-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkaana', '0005_remove_cloth_custom_id_remove_electronic_custom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='custom_id',
            field=models.CharField(default=6543, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronic',
            name='custom_id',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='custom_id',
            field=models.CharField(default=463, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
