# Generated by Django 4.2.1 on 2025-06-11 23:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dukkaana', '0005_cart_session_key_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 23, 32, 53, 177973, tzinfo=datetime.timezone.utc), verbose_name='valid to'),
        ),
    ]
