# Generated by Django 4.2.1 on 2023-07-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dukkaana', '0006_cloth_custom_id_electronic_custom_id_shoe_custom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='custom_id',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='custom_id',
        ),
        migrations.AddField(
            model_name='productimage',
            name='content_type',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
