# Generated by Django 4.2.1 on 2023-08-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkaana', '0008_cloth_image_electronic_image_shoe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
