# Generated by Django 4.2.1 on 2023-08-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukkaana', '0009_alter_cloth_description_alter_electronic_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electronic',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
